export const cartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
    DECREASE_CART_ITEM_QUANTITY: 'DECREASE_CART_ITEM_QUANTITY'
}
